### ISSUE TITLE
Watch OS support

### ISSUE THREAD

**Issue by SPopenko** [Rivukis/AutoEquatable#3]
@Rivukis  could you please update pod spec and add watch os as supported OS?
This will fix the next error:

```
 (watchOS 4.0) is not compatible with `AutoEquatable (1.3)`, which does not support `watchos`
```

**Comment by Rivukis** [comment]
Hi Sergey,
Great idea. I'll look at your pull request today, and try to have a release out today as well. If something comes up, I'll let you know.

Thank you,
Brian Radebaugh

**Comment by Rivukis** [comment]
I pushed out a new update that should allow WatchOS and TVOS targets to use AutoEquatable. Let me know if this doesn't work.

Also, I merged in your pull request, and added an extension for NSObject as well. Thanks for taking the time to help out!
